/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ZrUploadRouteImport } from './routes/zr-upload'
import { Route as ZrLieferantenRouteImport } from './routes/zr-lieferanten'
import { Route as ZrAbgleichRouteImport } from './routes/zr-abgleich'
import { Route as VerifyRouteImport } from './routes/verify'
import { Route as UploadCenterRouteImport } from './routes/upload-center'
import { Route as UnternehmenRouteImport } from './routes/unternehmen'
import { Route as SupportRouteImport } from './routes/support'
import { Route as SignaturenRouteImport } from './routes/signaturen'
import { Route as PruefungRouteImport } from './routes/pruefung'
import { Route as InternRouteImport } from './routes/intern'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ChecklisteRouteImport } from './routes/checkliste'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ZrReviewSessionIdRouteImport } from './routes/zr-review.$sessionId'
import { Route as ZrOutputSessionIdRouteImport } from './routes/zr-output.$sessionId'
import { Route as ZrCheckSessionIdRouteImport } from './routes/zr-check.$sessionId'

const ZrUploadRoute = ZrUploadRouteImport.update({
  id: '/zr-upload',
  path: '/zr-upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ZrLieferantenRoute = ZrLieferantenRouteImport.update({
  id: '/zr-lieferanten',
  path: '/zr-lieferanten',
  getParentRoute: () => rootRouteImport,
} as any)
const ZrAbgleichRoute = ZrAbgleichRouteImport.update({
  id: '/zr-abgleich',
  path: '/zr-abgleich',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyRoute = VerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const UploadCenterRoute = UploadCenterRouteImport.update({
  id: '/upload-center',
  path: '/upload-center',
  getParentRoute: () => rootRouteImport,
} as any)
const UnternehmenRoute = UnternehmenRouteImport.update({
  id: '/unternehmen',
  path: '/unternehmen',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const SignaturenRoute = SignaturenRouteImport.update({
  id: '/signaturen',
  path: '/signaturen',
  getParentRoute: () => rootRouteImport,
} as any)
const PruefungRoute = PruefungRouteImport.update({
  id: '/pruefung',
  path: '/pruefung',
  getParentRoute: () => rootRouteImport,
} as any)
const InternRoute = InternRouteImport.update({
  id: '/intern',
  path: '/intern',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ChecklisteRoute = ChecklisteRouteImport.update({
  id: '/checkliste',
  path: '/checkliste',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ZrReviewSessionIdRoute = ZrReviewSessionIdRouteImport.update({
  id: '/zr-review/$sessionId',
  path: '/zr-review/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const ZrOutputSessionIdRoute = ZrOutputSessionIdRouteImport.update({
  id: '/zr-output/$sessionId',
  path: '/zr-output/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const ZrCheckSessionIdRoute = ZrCheckSessionIdRouteImport.update({
  id: '/zr-check/$sessionId',
  path: '/zr-check/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/checkliste': typeof ChecklisteRoute
  '/dashboard': typeof DashboardRoute
  '/intern': typeof InternRoute
  '/pruefung': typeof PruefungRoute
  '/signaturen': typeof SignaturenRoute
  '/support': typeof SupportRoute
  '/unternehmen': typeof UnternehmenRoute
  '/upload-center': typeof UploadCenterRoute
  '/verify': typeof VerifyRoute
  '/zr-abgleich': typeof ZrAbgleichRoute
  '/zr-lieferanten': typeof ZrLieferantenRoute
  '/zr-upload': typeof ZrUploadRoute
  '/zr-check/$sessionId': typeof ZrCheckSessionIdRoute
  '/zr-output/$sessionId': typeof ZrOutputSessionIdRoute
  '/zr-review/$sessionId': typeof ZrReviewSessionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/checkliste': typeof ChecklisteRoute
  '/dashboard': typeof DashboardRoute
  '/intern': typeof InternRoute
  '/pruefung': typeof PruefungRoute
  '/signaturen': typeof SignaturenRoute
  '/support': typeof SupportRoute
  '/unternehmen': typeof UnternehmenRoute
  '/upload-center': typeof UploadCenterRoute
  '/verify': typeof VerifyRoute
  '/zr-abgleich': typeof ZrAbgleichRoute
  '/zr-lieferanten': typeof ZrLieferantenRoute
  '/zr-upload': typeof ZrUploadRoute
  '/zr-check/$sessionId': typeof ZrCheckSessionIdRoute
  '/zr-output/$sessionId': typeof ZrOutputSessionIdRoute
  '/zr-review/$sessionId': typeof ZrReviewSessionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/checkliste': typeof ChecklisteRoute
  '/dashboard': typeof DashboardRoute
  '/intern': typeof InternRoute
  '/pruefung': typeof PruefungRoute
  '/signaturen': typeof SignaturenRoute
  '/support': typeof SupportRoute
  '/unternehmen': typeof UnternehmenRoute
  '/upload-center': typeof UploadCenterRoute
  '/verify': typeof VerifyRoute
  '/zr-abgleich': typeof ZrAbgleichRoute
  '/zr-lieferanten': typeof ZrLieferantenRoute
  '/zr-upload': typeof ZrUploadRoute
  '/zr-check/$sessionId': typeof ZrCheckSessionIdRoute
  '/zr-output/$sessionId': typeof ZrOutputSessionIdRoute
  '/zr-review/$sessionId': typeof ZrReviewSessionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/checkliste'
    | '/dashboard'
    | '/intern'
    | '/pruefung'
    | '/signaturen'
    | '/support'
    | '/unternehmen'
    | '/upload-center'
    | '/verify'
    | '/zr-abgleich'
    | '/zr-lieferanten'
    | '/zr-upload'
    | '/zr-check/$sessionId'
    | '/zr-output/$sessionId'
    | '/zr-review/$sessionId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/checkliste'
    | '/dashboard'
    | '/intern'
    | '/pruefung'
    | '/signaturen'
    | '/support'
    | '/unternehmen'
    | '/upload-center'
    | '/verify'
    | '/zr-abgleich'
    | '/zr-lieferanten'
    | '/zr-upload'
    | '/zr-check/$sessionId'
    | '/zr-output/$sessionId'
    | '/zr-review/$sessionId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/checkliste'
    | '/dashboard'
    | '/intern'
    | '/pruefung'
    | '/signaturen'
    | '/support'
    | '/unternehmen'
    | '/upload-center'
    | '/verify'
    | '/zr-abgleich'
    | '/zr-lieferanten'
    | '/zr-upload'
    | '/zr-check/$sessionId'
    | '/zr-output/$sessionId'
    | '/zr-review/$sessionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  ChecklisteRoute: typeof ChecklisteRoute
  DashboardRoute: typeof DashboardRoute
  InternRoute: typeof InternRoute
  PruefungRoute: typeof PruefungRoute
  SignaturenRoute: typeof SignaturenRoute
  SupportRoute: typeof SupportRoute
  UnternehmenRoute: typeof UnternehmenRoute
  UploadCenterRoute: typeof UploadCenterRoute
  VerifyRoute: typeof VerifyRoute
  ZrAbgleichRoute: typeof ZrAbgleichRoute
  ZrLieferantenRoute: typeof ZrLieferantenRoute
  ZrUploadRoute: typeof ZrUploadRoute
  ZrCheckSessionIdRoute: typeof ZrCheckSessionIdRoute
  ZrOutputSessionIdRoute: typeof ZrOutputSessionIdRoute
  ZrReviewSessionIdRoute: typeof ZrReviewSessionIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/zr-upload': {
      id: '/zr-upload'
      path: '/zr-upload'
      fullPath: '/zr-upload'
      preLoaderRoute: typeof ZrUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zr-lieferanten': {
      id: '/zr-lieferanten'
      path: '/zr-lieferanten'
      fullPath: '/zr-lieferanten'
      preLoaderRoute: typeof ZrLieferantenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zr-abgleich': {
      id: '/zr-abgleich'
      path: '/zr-abgleich'
      fullPath: '/zr-abgleich'
      preLoaderRoute: typeof ZrAbgleichRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify': {
      id: '/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof VerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upload-center': {
      id: '/upload-center'
      path: '/upload-center'
      fullPath: '/upload-center'
      preLoaderRoute: typeof UploadCenterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unternehmen': {
      id: '/unternehmen'
      path: '/unternehmen'
      fullPath: '/unternehmen'
      preLoaderRoute: typeof UnternehmenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signaturen': {
      id: '/signaturen'
      path: '/signaturen'
      fullPath: '/signaturen'
      preLoaderRoute: typeof SignaturenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pruefung': {
      id: '/pruefung'
      path: '/pruefung'
      fullPath: '/pruefung'
      preLoaderRoute: typeof PruefungRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intern': {
      id: '/intern'
      path: '/intern'
      fullPath: '/intern'
      preLoaderRoute: typeof InternRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkliste': {
      id: '/checkliste'
      path: '/checkliste'
      fullPath: '/checkliste'
      preLoaderRoute: typeof ChecklisteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zr-review/$sessionId': {
      id: '/zr-review/$sessionId'
      path: '/zr-review/$sessionId'
      fullPath: '/zr-review/$sessionId'
      preLoaderRoute: typeof ZrReviewSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zr-output/$sessionId': {
      id: '/zr-output/$sessionId'
      path: '/zr-output/$sessionId'
      fullPath: '/zr-output/$sessionId'
      preLoaderRoute: typeof ZrOutputSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zr-check/$sessionId': {
      id: '/zr-check/$sessionId'
      path: '/zr-check/$sessionId'
      fullPath: '/zr-check/$sessionId'
      preLoaderRoute: typeof ZrCheckSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  ChecklisteRoute: ChecklisteRoute,
  DashboardRoute: DashboardRoute,
  InternRoute: InternRoute,
  PruefungRoute: PruefungRoute,
  SignaturenRoute: SignaturenRoute,
  SupportRoute: SupportRoute,
  UnternehmenRoute: UnternehmenRoute,
  UploadCenterRoute: UploadCenterRoute,
  VerifyRoute: VerifyRoute,
  ZrAbgleichRoute: ZrAbgleichRoute,
  ZrLieferantenRoute: ZrLieferantenRoute,
  ZrUploadRoute: ZrUploadRoute,
  ZrCheckSessionIdRoute: ZrCheckSessionIdRoute,
  ZrOutputSessionIdRoute: ZrOutputSessionIdRoute,
  ZrReviewSessionIdRoute: ZrReviewSessionIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
