/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyRouteImport } from './routes/verify'
import { Route as UploadCenterRouteImport } from './routes/upload-center'
import { Route as UnternehmenRouteImport } from './routes/unternehmen'
import { Route as SupportRouteImport } from './routes/support'
import { Route as SignaturenRouteImport } from './routes/signaturen'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ChecklisteRouteImport } from './routes/checkliste'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'

const VerifyRoute = VerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const UploadCenterRoute = UploadCenterRouteImport.update({
  id: '/upload-center',
  path: '/upload-center',
  getParentRoute: () => rootRouteImport,
} as any)
const UnternehmenRoute = UnternehmenRouteImport.update({
  id: '/unternehmen',
  path: '/unternehmen',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const SignaturenRoute = SignaturenRouteImport.update({
  id: '/signaturen',
  path: '/signaturen',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ChecklisteRoute = ChecklisteRouteImport.update({
  id: '/checkliste',
  path: '/checkliste',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/checkliste': typeof ChecklisteRoute
  '/dashboard': typeof DashboardRoute
  '/signaturen': typeof SignaturenRoute
  '/support': typeof SupportRoute
  '/unternehmen': typeof UnternehmenRoute
  '/upload-center': typeof UploadCenterRoute
  '/verify': typeof VerifyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/checkliste': typeof ChecklisteRoute
  '/dashboard': typeof DashboardRoute
  '/signaturen': typeof SignaturenRoute
  '/support': typeof SupportRoute
  '/unternehmen': typeof UnternehmenRoute
  '/upload-center': typeof UploadCenterRoute
  '/verify': typeof VerifyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/checkliste': typeof ChecklisteRoute
  '/dashboard': typeof DashboardRoute
  '/signaturen': typeof SignaturenRoute
  '/support': typeof SupportRoute
  '/unternehmen': typeof UnternehmenRoute
  '/upload-center': typeof UploadCenterRoute
  '/verify': typeof VerifyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/checkliste'
    | '/dashboard'
    | '/signaturen'
    | '/support'
    | '/unternehmen'
    | '/upload-center'
    | '/verify'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/checkliste'
    | '/dashboard'
    | '/signaturen'
    | '/support'
    | '/unternehmen'
    | '/upload-center'
    | '/verify'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/checkliste'
    | '/dashboard'
    | '/signaturen'
    | '/support'
    | '/unternehmen'
    | '/upload-center'
    | '/verify'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  ChecklisteRoute: typeof ChecklisteRoute
  DashboardRoute: typeof DashboardRoute
  SignaturenRoute: typeof SignaturenRoute
  SupportRoute: typeof SupportRoute
  UnternehmenRoute: typeof UnternehmenRoute
  UploadCenterRoute: typeof UploadCenterRoute
  VerifyRoute: typeof VerifyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify': {
      id: '/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof VerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upload-center': {
      id: '/upload-center'
      path: '/upload-center'
      fullPath: '/upload-center'
      preLoaderRoute: typeof UploadCenterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unternehmen': {
      id: '/unternehmen'
      path: '/unternehmen'
      fullPath: '/unternehmen'
      preLoaderRoute: typeof UnternehmenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signaturen': {
      id: '/signaturen'
      path: '/signaturen'
      fullPath: '/signaturen'
      preLoaderRoute: typeof SignaturenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkliste': {
      id: '/checkliste'
      path: '/checkliste'
      fullPath: '/checkliste'
      preLoaderRoute: typeof ChecklisteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  ChecklisteRoute: ChecklisteRoute,
  DashboardRoute: DashboardRoute,
  SignaturenRoute: SignaturenRoute,
  SupportRoute: SupportRoute,
  UnternehmenRoute: UnternehmenRoute,
  UploadCenterRoute: UploadCenterRoute,
  VerifyRoute: VerifyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
